default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: remoteblog
  username: rails
  host: localhost
  password: password

test:
  <<: *default
  database: remoteblog_test

production:
  <<: *default
  database: ancient-depths-79958_production
  username: ancient-depths-79958
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>